items = [{'name': 'Barrel of bait', 'cost': '50,000', 'quantity': '1',
          'use': '10% chance to gain an additional catch for 3 minutes.'},
         {'name': 'Tangled fishbowl', 'cost': '50,000', 'quantity': '1',
          'use': '5% Fishing experience boost for 3 minutes.'},
         {'name': 'Broken fishing rod', 'cost': '50,000', 'quantity': '1',
          'use': '5-10% bonus catch rate for 3-30 minutes.'},
         {'name': 'Small goebie burial charm', 'cost': '50,000', 'quantity': '1',
          'use': '50 [[Reputation (Mazcab)|Goebie Reputation]] or 50 [[Teci]]'},
         {'name': 'Goebie burial charm', 'cost': '100,000', 'quantity': '1',
          'use': '100 [[Reputation (Mazcab)|Goebie Reputation]] or 100 [[Teci]]'},
         {'name': 'Menaphite gift offering (small)', 'cost': '100,000', 'quantity': '1',
          'use': 'Variety of rewards, see page'},
         {'name': 'Menaphite gift offering (medium)', 'cost': '300,000', 'quantity': '1',
          'use': 'Variety of rewards, see page'},
         {'name': 'Unstable air rune', 'cost': '250,000', 'quantity': '1',
          'use': '5,000 [[Runespan#Rewards|Runespan points]]'},
         {'name': 'Anima crystal', 'cost': '150,000', 'quantity': '1',
          'use': '500 [[Reputation (Heart of Gielinor)|faction reputation]]'},
         {'name': 'Slayer VIP Coupon', 'cost': '200,000', 'quantity': '1',
          'use': 'Redeemed for 1-7 [[Slayer VIP ticket]]s'},
         {'name': 'D&D token (daily)', 'cost': '250,000', 'quantity': '1', 'use': 'One-time use to reset a daily [[D&D]]'},
         {'name': 'Unfocused damage enhancer', 'cost': '500,000', 'quantity': '1',
          'use': 'Allows choice of any damage enhancer at the cost of lower charges'},
         {'name': 'Sacred clay (Deep Sea Fishing)', 'cost': '600,000', 'quantity': '1',
          'use': '50-100 [[Stealing Creation/Rewards#Reward shop|Stealing Creation points]]'},
         {'name': 'Shattered anima', 'cost': '750,000', 'quantity': '500,000-2,000,000',
          'use': 'See shop [[Shattered Worlds/Rewards|here]]'},
         {'name': 'Advanced pulse core', 'cost': '800,000', 'quantity': "'1-3'",
          'use': '50% extra experience that does not stack with other sources of bonus experience, up to the equivalent of a Medium prismatic lamp.'},
         {'name': 'Livid plant (Deep Sea Fishing)',
          'cost': "1,000,000", 'quantity': '1',
          'use': '10,000 to 40,000 [[produce points]]'},
         {'name': 'Gift for the Reaper', 'cost': '1,250,000', 'quantity': '1', 'use': '20 [[Reaper points]]'},
         {'name': 'Silverhawk down', 'cost': '1,500,000', 'quantity': "'50-100'",
          'use': 'See [[silverhawk down]] for experience calculator'},
         {'name': 'Large goebie burial charm', 'cost': '150,000', 'quantity': '1',
          'use': '150 [[Reputation (Mazcab)|Goebie Reputation]] or 150 [[Teci]]'},
         {'name': 'Message in a bottle (Deep Sea Fishing)', 'cost': '200,000', 'quantity': '1',
          'use': 'One time choice between three [[Deep Sea Fishing]] boosts'},
         {'name': 'Dragonkin lamp', 'cost': '250,000', 'quantity': '1',
          'use': 'Rewards a set amount of experience and a 1/100 chance to obtain [[Effy]]'},
         {'name': 'Dungeoneering Wildcard', 'cost': '400,000', 'quantity': "1-3",
          'use': 'Consuming the card inside [[Daemonheim]] rewards 50% extra experience and [[dungeoneering token|token]]s'},
         {'name': 'Menaphite gift offering (large)', 'cost': '500,000', 'quantity': '1',
          'use': 'Variety of rewards, see page'},
         {'name': 'Taijitu', 'cost': '800,000', 'quantity': "3-5",
          'use': 'Secondary currency used for the [[Waiko Reward Shop]].'},
         {'name': 'D&D token (weekly)', 'cost': '400,000', 'quantity': '1', 'use': 'One-time use to reset a weekly [[D&D]]'},
         {'name': 'D&D token (monthly)', 'cost': '1,000,000', 'quantity': '1',
          'use': 'One-time use to reset a monthly [[D&D]]'},
         {'name': 'Starved ancient effigy', 'cost': '1,000,000', 'quantity': '1',
          'use': 'Rewards a set amount of experience in multiple skills and a 1/100 chance to obtain [[Effy]]'},
         {'name': 'Harmonic dust', 'cost': '2,000,000', 'quantity': "'500-1000'",
          'use': 'Used for creating [[crystal tool]]s'},
         {'name': 'Crystal triskelion', 'cost': '2,000,000', 'quantity': '1',
          'use': 'Deposited in a cliff face south of [[Rellekka]] to obtain a [[clue scroll (elite)]] and variety of other rewards'},
         {'name': 'Deathtouched dart', 'cost': '5,000,000', 'quantity': '1', 'use': 'Insta-kill majority of all NPCs'},
         {'name': 'Unfocused reward enhancer', 'cost': '10,000,000', 'quantity': '1',
          'use': 'Allows choice of any reward enhancer at the cost of lower charges'}, ]


def get_attrs(name):
    for dic in items:
        if dic["name"] == name:
            return [dic["cost"], dic["quantity"], dic["use"]]

