item_list = ['Small goebie burial charm',
             'Goebie burial charm',
             'Menaphite gift offering (small)',
             'Menaphite gift offering (medium)',
             'Unstable air rune',
             'Anima crystal',
             'Slayer VIP Coupon',
             'D&D token (daily)',
             'Unfocused damage enhancer',
             'Sacred clay',
             'Shattered anima',
             'Advanced pulse core',
             'Livid plant',
             'Gift for the Reaper',
             'Silverhawk down',
             'Large goebie burial charm',
             'Message in a bottle',
             'Dragonkin lamp',
             'Dungeoneering Wildcard',
             'Menaphite gift offering (large)',
             'Taijitu',
             'D&D token (weekly)',
             'D&D token (monthly)',
             'Starved ancient effigy',
             'Harmonic dust',
             'Crystal triskelion',
             'Deathtouched dart',
             'Unfocused reward enhancer',
             'Uncharted island map',
             'Barrel of bait',
             'Tangled fishbowl']

