item_list = ['Small goebie burial charm\n'
             'Goebie burial charm\n'
             'Menaphite gift offering (small)\n'
             'Menaphite gift offering (medium)\n'
             'Unstable air rune\n'
             'Anima crystal\n'
             'Slayer VIP Coupon\n'
             'D&D token (daily)\n'
             'Unfocused damage enhancer\n'
             'Sacred clay\n'
             'Shattered anima\n'
             'Advanced pulse core\n'
             'Livid plant\n'
             'Gift for the Reaper\n'
             'Silverhawk down\n'
             'Large goebie burial charm\n'
             'Message in a bottle\n'
             'Dragonkin lamp\n'
             'Dungeoneering Wildcard\n'
             'Menaphite gift offering (large)\n'
             'Taijitu\n'
             'D&D token (weekly)\n'
             'D&D token (monthly)\n'
             'Starved ancient effigy\n'
             'Harmonic dust\n'
             'Crystal triskelion\n'
             'Deathtouched dart\n'
             'Unfocused reward enhancer']

